### ISSUE TITLE
Exposed .env file

### ISSUE THREAD

**Issue by Danielp93** [earlquinlan/level_up#73]
Hi, 

While trying out a new OSINT tool, I noticed that this repository exposes it's .env file (and commits thereof). May I suggest to add the .env file to your .gitignore again (reverse 4238139317b8d427a0b32232dcf6125c12ba0561) since, for example, the Mapbox API keys for users _danielsperling_ and _maxfrda_ are now in the open and can be used by anyone. Maybe take a look at https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository to clean the file from your git commit history and/or generate new API keys at mapbox.

I noticed this repo is part of a bootcamp, so it's probably a good idea to mention that a .env file is a secret file in most cases. 

If this is non-sensitive and part of an example etc. I apologise for meddling and feel free to ignore this issue.

Greetings, 
Daniël

**Comment by earlquinlan** [comment]
Thanks Daniël!
